"""Export snapshots to various formats (shell script, Dockerfile, requirements.txt)."""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from envforge.snapshot import EnvSnapshot


SUPPORTED_FORMATS = ("shell", "dockerfile", "requirements")


def export_as_shell(snapshot: "EnvSnapshot") -> str:
    """Export snapshot as a portable shell setup script."""
    lines = ["#!/usr/bin/env bash", "# Generated by envforge", "set -euo pipefail", ""]

    if snapshot.env_vars:
        lines.append("# Environment variables")
        for key, value in sorted(snapshot.env_vars.items()):
            escaped = value.replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'export {key}="{escaped}"')
        lines.append("")

    if snapshot.pip_packages:
        lines.append("# Python packages")
        lines.append("pip install \\")
        pkg_list = [
            f"  {pkg}=={ver}" for pkg, ver in sorted(snapshot.pip_packages.items())
        ]
        lines.append(" \\\n".join(pkg_list))
        lines.append("")

    return "\n".join(lines)


def export_as_dockerfile(snapshot: "EnvSnapshot") -> str:
    """Export snapshot as a Dockerfile snippet."""
    lines = ["# Generated by envforge", ""]

    python_ver = snapshot.python_version or "3.11"
    major_minor = ".".join(python_ver.split(".")[:2])
    lines.append(f"FROM python:{major_minor}-slim")
    lines.append("")

    if snapshot.env_vars:
        lines.append("# Environment variables")
        for key, value in sorted(snapshot.env_vars.items()):
            escaped = value.replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'ENV {key}="{escaped}"')
        lines.append("")

    if snapshot.pip_packages:
        pkg_pins = " ".join(
            f"{pkg}=={ver}" for pkg, ver in sorted(snapshot.pip_packages.items())
        )
        lines.append(f"RUN pip install --no-cache-dir {pkg_pins}")
        lines.append("")

    return "\n".join(lines)


def export_as_requirements(snapshot: "EnvSnapshot") -> str:
    """Export pip packages as a requirements.txt file."""
    lines = ["# Generated by envforge"]
    for pkg, ver in sorted(snapshot.pip_packages.items()):
        lines.append(f"{pkg}=={ver}")
    return "\n".join(lines) + "\n"


def export_snapshot(snapshot: "EnvSnapshot", fmt: str) -> str:
    """Dispatch export to the appropriate formatter."""
    if fmt not in SUPPORTED_FORMATS:
        raise ValueError(f"Unsupported format '{fmt}'. Choose from: {SUPPORTED_FORMATS}")
    if fmt == "shell":
        return export_as_shell(snapshot)
    if fmt == "dockerfile":
        return export_as_dockerfile(snapshot)
    return export_as_requirements(snapshot)


def write_export(snapshot: "EnvSnapshot", fmt: str, path: str) -> None:
    """Write exported snapshot to a file."""
    content = export_snapshot(snapshot, fmt)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)
