"""Reproducer module: generate shell scripts to reproduce a captured environment."""

from __future__ import annotations

import os
from typing import Optional

from envforge.snapshot import EnvSnapshot


SHELL_HEADER = """#!/usr/bin/env bash
# Generated by envforge — do not edit manually
set -euo pipefail
"""


def generate_env_exports(snapshot: EnvSnapshot) -> str:
    """Return shell export statements for all captured env vars."""
    lines = ["# Environment variables"]
    for key, value in sorted(snapshot.env_vars.items()):
        escaped = value.replace('"', '\\"')
        lines.append(f'export {key}="{escaped}"')
    return "\n".join(lines)


def generate_pip_install(snapshot: EnvSnapshot) -> str:
    """Return pip install commands for captured packages."""
    if not snapshot.pip_packages:
        return "# No pip packages captured"
    lines = ["# Python pip packages"]
    pkgs = " ".join(
        f'"{pkg}"' for pkg in sorted(snapshot.pip_packages)
    )
    lines.append(f"pip install --quiet {pkgs}")
    return "\n".join(lines)


def generate_version_checks(snapshot: EnvSnapshot) -> str:
    """Return advisory version-check comments."""
    lines = ["# Runtime versions (advisory — install manually if needed)"]
    if snapshot.python_version:
        lines.append(f"# Python: {snapshot.python_version}")
    if snapshot.node_version:
        lines.append(f"# Node:   {snapshot.node_version}")
    return "\n".join(lines)


def build_reproduction_script(
    snapshot: EnvSnapshot,
    include_env: bool = True,
    include_packages: bool = True,
) -> str:
    """Assemble a complete bash reproduction script from a snapshot."""
    sections = [SHELL_HEADER, generate_version_checks(snapshot)]
    if include_env:
        sections.append(generate_env_exports(snapshot))
    if include_packages:
        sections.append(generate_pip_install(snapshot))
    sections.append("\necho \"Environment reproduced successfully.\"")  
    return "\n\n".join(sections)


def write_reproduction_script(
    snapshot: EnvSnapshot,
    output_path: str,
    include_env: bool = True,
    include_packages: bool = True,
) -> str:
    """Write the reproduction script to *output_path* and make it executable."""
    script = build_reproduction_script(
        snapshot,
        include_env=include_env,
        include_packages=include_packages,
    )
    with open(output_path, "w", encoding="utf-8") as fh:
        fh.write(script)
    os.chmod(output_path, 0o755)
    return output_path
